/*
Beginner = 1
Journeyman = 2

Warrior = 7
Barbarian = 8
Squire = 9

Archer = 19
Bowman = 20
Hunter = 21

Mage = 31
Wizard = 32
Shaman = 33
*/
var charSubclassMap = {
    2 : 1,
    8 : 7,
    9 : 7,
    20: 19,
    21 : 19,
    33 : 31,
    32 : 31
};

var skillIndexMap = {
    0 : "character",
    1 : "mining",
    2 : "smithing",
    3 : "chopping",
    4 : "fishing",
    5 : "alchemy",
    6 : "catching",
    7 : "trapping",
    8 : "construction",
    9 : "worship"
};

var classIndexMap = {
    1 : "Beginner",
    2 : "Journeyman",
    3 : "Maestro",
    4 : "Virtuoso",
    5 : "Infinilyte",
    6 : "Rage Basics",
    7 : "Warrior",
    8 : "Barbarian",
    9 : "Squire",
    10 : "Blood Berserker",
    11 : "Death Bringer",
    12 : "Divine Knight",
    13 : "Royal Guardian",
    14 : "Filler",
    15 : "Filler",
    16 : "Filler",
    17 : "Filler",
    18 : "Calm Basics",
    19 : "Archer",
    20 : "Bowman",
    21 : "Hunter",
    22 : "Siege Breaker",
    23 : "Mayheim",
    24 : "Wind Walker",
    25 : "Beast Master",
    26 : "Filler",
    27 : "Filler",
    28 : "Filler",
    29 : "Filler",
    30 : "Savvy Basics",
    31 : "Mage",
    32 : "Wizard",
    33 : "Shaman",
    34 : "Elemental Sorcerer",
    35 : "Spiritual Monk",
    36 : "Bubonic Conjuror",
    37 : "Arcane Cultist",
    38 : "Filler",
    39 : "Filler",
    40 : "Filler",
    41 : "Filler",
};

var obolNameMap = {
    "ObolAmarokA" : "Granite Obol of Amarok's Stare",
    "ObolBronze0" : "Bronze STR Obol",
    "ObolBronze1" : "Bronze AGI Obol",
    "ObolBronze2" : "Bronze WIS Obol",
    "ObolBronze3" : "Bronze LUK Obol",
    "ObolBronzeCatching" : "Bronze Obol of Few Flies",
    "ObolBronzeChoppin" : "Bronze Obol of Chippin Chops",
    "ObolBronzeDamage" : "Bronze Obol of Puny Damage",
    "ObolBronzeFishing" : "Bronze Obol of Finite Fish",
    "ObolBronzeMining" : "Bronze Obol of Small Swings",
    "ObolBronzePop" : "Bronze Obol of Pop",
    "ObolEfauntA" : "Skeletal Obol of Efaunt's Gaze",
    "ObolGold0" : "Gold STR Obol",
    "ObolGold1" : "Gold AGI Obol",
    "ObolGold2" : "Gold WIS Obol",
    "ObolGold3" : "Gold LUK Obol",
    "ObolGoldCatching" : "Golden Obol of Insane Insects",
    "ObolGoldChoppin" : "Golden Obol of Huge Hackin",
    "ObolGoldDamage" : "Golden Obol of Big Boy Damage",
    "ObolGoldFishing" : "Golden Obol of Crazy Carp",
    "ObolGoldMining" : "Golden Obol of Diligent Digging",
    "ObolGoldMoney" : "Golden Obol of Plentiful Riches",
    "ObolPinkCatching" : "Dementia Obol of Idk Yet",
    "ObolPinkChoppin" : "Dementia Obol of WOWOWOWWO",
    "ObolPinkDamage" : "Dementia Obol of Infinite Damage",
    "ObolPinkFishing" : "Dementia Obol of Monument Marlins",
    "ObolPinkLuck" : "Dementia Obol of Never Ending Luck",
    "ObolPinkMining" : "Dementia Obol of Magisterial Metals",
    "ObolPlatinumCatching" : "Platinum Obol of Idk Yet",
    "ObolPlatinumChoppin" : "Platinum Obol of Lumby Loggo",
    "ObolPlatinumDamage" : "Platinum Obol of Lethal Damage",
    "ObolPlatinumFishing" : "Platinum Obol of Tremendous Trout",
    "ObolPlatinumMining" : "Platinum Obol of Dwarven Delving",
    "ObolPlatinumSpeed" : "Platinum Obol of Blinding Speed",
    "ObolSilver0" : "Silver STR Obol",
    "ObolSilver1" : "Silver AGI Obol",
    "ObolSilver2" : "Silver WIS Obol",
    "ObolSilver3" : "Silver LUK Obol",
    "ObolSilverCatching" : "Silver Obol of Big Bugs",
    "ObolSilverChoppin" : "Silver Obol of Big Bark",
    "ObolSilverDamage" : "Silver Obol of Little Damage",
    "ObolSilverFishing" : "Silver Obol of Puny Pikes",
    "ObolSilverLuck" : "Silver Obol of Double Sixes",
    "ObolSilverMining" : "Silver Obol of Moderate Mining",
    "ObolSilverMoney" : "Silver Obol of Pocket Change",
    "NOT_FOUND" : "None"
};

//maps stored stamp ID to it's display name
var stampIdToDisplayMap = {
    0 : "Sword Stamp",
    1 : "Heart Stamp",
    2 : "Mana Stamp",
    3 : "Tomahawk Stamp",
    4 : "Target Stamp",
    5 : "Shield Stamp",
    6 : "Longsword Stamp",
    7 : "Kapow Stamp",
    8 : "Fist Stamp",
    9 : "Battleaxe Stamp",
    10 : "Agile Stamp",
    11 : "Vitality Stamp",
    12 : "Book Stamp",
    13 : "Manamoar Stamp",
    14 : "Clover Stamp",
    15 : "Scimitar Stamp",
    16 : "Bullseye Stamp",
    17 : "Feather Stamp",
    18 : "Polearm Stamp",
    19 : "Violence Stamp",
    20 : "Buckler Stamp",
    21 : "FILLER",
    22 : "Sukka Foo",
    23 : "Arcane Stamp",
    24 : "FILLER",
    25 : "Steve Sword",
    26 : "Blover Stamp",
    27 : "Stat Graph Stamp",
    28 : "FILLER",
    29 : "FILLER",
    30 : "FILLER",
    31 : "FILLER",
    32 : "FILLER",
    33 : "FILLER",
    34 : "FILLER",
    1000 : "Pickaxe Stamp",
    1001 : "Hatchet Stamp",
    1002 : "Anvil Zoomer|Stamp",
    1003 : "Lil' Mining Baggy|Stamp",
    1004 : "Twin Ores Stamp",
    1005 : "Choppin' Bag|Stamp",
    1006 : "Duplogs Stamp",
    1007 : "Matty Bag Stamp",
    1008 : "Smart Dirt Stamp",
    1009 : "Cool Diggy Tool|Stamp",
    1010 : "High IQ Lumber|Stamp",
    1011 : "Swag Swingy Tool|Stamp",
    1012 : "Alch Go Brrr|Stamp",
    1013 : "Brainstew Stamps",
    1014 : "Drippy Drop Stamp",
    1015 : "Droplots Stamp",
    1016 : "Fishing Rod Stamp",
    1017 : "Fishhead Stamp",
    1018 : "Catch Net Stamp",
    1019 : "Fly Intel Stamp",
    1020 : "Bag o Heads Stamp",
    1021 : "Holy Mackerel|Stamp",
    1022 : "Bugsack Stamp",
    1023 : "Buzz Buzz Stamp",
    2000 : "Questin Stamp",
    2001 : "Mason Jar Stamp",
    2002 : "Crystallin",
    2003 : "Blank",
    2004 : "Apple Stamp",
    2005 : "Potion Stamp",
    2006 : "Golden Apple|Stamp",
    2007 : "Blank",
    2008 : "Card Stamp",
    2009 : "Blank",
    2010 : "Blank",
    2011 : "Blank",
    2012 : "Talent I Stamp",
    2013 : "Talent II Stamp",
    2014 : "Talent III Stamp",
    2015 : "Talent IV Stamp",
    2016 : "Talent V Stamp",
    2017 : "Talent S Stamp",    
};