var companionItemList = [ //TODO this needs updated!
  "Inventory Bag U",
  "Inventory Bag V",
  "Inventory Bag W",
  "Inventory Bag X",
  "Inventory Bag Y",
  "Inventory Bag Z",
  "Storage Chest 1",
  "Storage Chest 2",
  "Storage Chest 3",
  "Storage Chest 4",
  "Storage Chest 5",
  "Storage Chest 6",
  "Storage Chest 7",
  "Storage Chest 8",
  "Storage Chest 9",
  "Storage Chest 10",
  "Storage Chest 11",
  "Storage Chest 12",
  "Storage Chest 13",
  "Storage Chest 14",
  "Storage Chest 15",
  "Storage Chest 16",
  "Storage Chest 17",
  "Storage Chest 18",
  "Storage Chest 19",
  "Storage Chest 20",
  "Storage Chest 21",
  "Storage Chest 90",
  "Storage Chest 91",
  "Storage Chest 92",
  "Storage Chest 93",
  "Storage Chest 94",
  "Storage Chest 95",
  "Storage Chest 96",
  "Storage Chest 97",
  "Storage Chest 98",
  "Storage Chest 99",
  "Storage Chest 99B",
  "Storage Chest 99C",
  "Dank Paypay Chest",
  "Sword Stamp",
  "Heart Stamp",
  "Mana Stamp",
  "Tomahawk Stamp",
  "Target Stamp",
  "Shield Stamp",
  "Longsword Stamp",
  "Kapow Stamp",
  "Fist Stamp",
  "Battleaxe Stamp",
  "Agile Stamp",
  "Vitality Stamp",
  "Book Stamp",
  "Manamoar Stamp",
  "Clover Stamp",
  "Scimitar Stamp",
  "Bullseye Stamp",
  "Feather Stamp",
  "Polearm Stamp",
  "Violence Stamp",
  "Buckler Stamp",
  "Sukka Foo Stamp",
  "Arcane Stamp",
  "Steve Sword Stamp",
  "Blover Stamp",
  "Stat Graph Stamp",
  "Pickaxe Stamp",
  "Hatchet Stamp",
  "Anvil Zoomer Stamp",
  "Lil' Mining Baggy Stamp",
  "Twin Ores Stamp",
  "Choppin' Bag Stamp",
  "Duplogs Stamp",
  "Matty Bag Stamp",
  "Smart Dirt Stamp",
  "Cool Diggy Tool Stamp",
  "High IQ Lumber Stamp",
  "Swag Swingy Tool Stamp",
  "Smartas Smithing Stamp",
  "Alch Go Brrr Stamp",
  "Brainstew Stamp",
  "Drippy Drop Stamp",
  "Droplots Stamp",
  "Fishing Rod Stamp",
  "Fishhead Stamp",
  "Catch Net Stamp",
  "Fly Intel Stamp",
  "Bag o Heads Stamp",
  "Holy Mackerel Stamp",
  "Bugsack Stamp",
  "Buzz Buzz Stamp",
  "Hidey Box Stamp",
  "Purp Froge Stamp",
  "Spikemouth Stamp",
  "Sample Stamp",
  "Saw Stamp",
  "Flowin Stamp",
  "Banked Pts Stamp",
  "Questin Stamp",
  "Mason Jar Stamp",
  "Crystallin Stamp",
  "Apple Stamp",
  "Potion Stamp",
  "Golden Apple Stamp",
  "Card Stamp",
  "Talent I Stamp",
  "Talent II Stamp",
  "Talent III Stamp",
  "Talent IV Stamp",
  "Talent V Stamp",
  "Talent S Stamp",
  "Multikill Stamp",
  "Biblio Stamp",
];
