//what should be searched through to find
var companionCharInventoryPouchList = [
  "Inventory Bag A",
  "Inventory Bag B",
  "Inventory Bag C",
  "Inventory Bag D",
  "Inventory Bag H",
  "Inventory Bag G",
  "Inventory Bag E",
  "Inventory Bag F",
  "Inventory Bag I",
  "Snakeskinventory Bag",
  "Totally Normal And Not Fake Bag",
  "Mamooth Hide Bag",
  "Bummo Bag",
  "Shivering Sack",
  "Sandy Satchel",
  "Blunderbag",
  "Capitalist Case",
  "Wealthy Wallet",
  "Prosperous Pouch",
  "Sack of Success"
];

var companionCharMaterialPouchList = [
  "Mini Materials Pouch",
  "Cramped Materials Pouch",
  "Small Materials Pouch",
  "Average Materials Pouch",
  "Sizable Materials Pouch",
  "Big Materials Pouch",
  "Large Materials Pouch",
  "Miniature Mining Pouch",
  "Cramped Mining Pouch",
  "Small Mining Pouch",
  "Average Mining Pouch",
  "Sizable Mining Pouch",
  "Big Mining Pouch",
  "Large Mining Pouch",
  "Miniature Fish Pouch",
  "Cramped Fish Pouch",
  "Small Fish Pouch",
  "Average Fish Pouch",
  "Sizable Fish Pouch",
  "Big Fish Pouch",
  "Large Fish Pouch",
  "Miniscule Food Pouch",
  "Cramped Food Pouch",
  "Small Food Pouch",
  "Average Food Pouch",
  "Sizable Food Pouch",
  "Big Food Pouch",
  "Large Food Pouch",
  "Small Critter Pouch",
  "Sizable Critter Pouch",
  "Big Critter Pouch",
  "Large Critter Pouch",
  "Miniature Bug Pouch",
  "Cramped Bug Pouch",
  "Small Bug Pouch",
  "Average Bug Pouch",
  "Sizable Bug Pouch",
  "Big Bug Pouch",
  "Large Bug Pouch",
  "Small Soul Pouch",
  "Sizable Soul Pouch",
  "Big Soul Pouch",
  "Large Soul Pouch",
  "Miniature Choppin Pouch",
  "Cramped Choppin Pouch",
  "Small Choppin Pouch",
  "Average Choppin Pouch",
  "Sizable Choppin Pouch",
  "Big Choppin Pouch",
  "Large Choppin Pouch",
]